export default [
  { text: "10 分钟快速搞懂 Lambda 表达式", link: "/知识碎片/10 分钟快速搞懂 Lambda 表达式" },
  {
    text: "1秒将本地SpringBoot项目jar包部署到Linux环境",
    link: "/知识碎片/1秒将本地SpringBoot项目jar包部署到Linux环境",
  },
  { text: "4 种方法，快速初始化 Java 项目", link: "/知识碎片/4 种方法，快速初始化 Java 项目" },
  { text: "Bean 拷贝之 MapStruct", link: "/知识碎片/Bean 拷贝之 MapStruct" },
  { text: "DDD 是什么？", link: "/知识碎片/DDD 是什么？" },
  { text: "DTO转VO工具", link: "/知识碎片/DTO转VO工具" },
  { text: "EasyExcel 导出文件", link: "/知识碎片/EasyExcel 导出文件" },
  { text: "ElasticSearch 基础概念与入门使用", link: "/知识碎片/ElasticSearch 基础概念与入门使用" },
  { text: "Git 提交竟然还能这么用？", link: "/知识碎片/Git 提交竟然还能这么用？" },
  { text: "Hexo+Github+Netlify博客搭建教程", link: "/知识碎片/Hexo+Github+Netlify博客搭建教程" },
  { text: "IDEA 同时关联 GitHub 和 Gitee 远程仓库", link: "/知识碎片/IDEA 同时关联 GitHub 和 Gitee 远程仓库" },
  { text: "IDEA+Docker远程部署SpringBoot项目", link: "/知识碎片/IDEA+Docker远程部署SpringBoot项目" },
  { text: "Java 8 新特性：Stream 流快速入门", link: "/知识碎片/Java 8 新特性：Stream 流快速入门" },
  { text: "Java 实现 GitHub 第三方登录详解", link: "/知识碎片/Java 实现 GitHub 第三方登录详解" },
  { text: "LiteFlow 编排式编程简单介绍", link: "/知识碎片/LiteFlow 编排式编程简单介绍" },
  { text: "MarkDown 文本解析成 HTML 并生成大纲", link: "/知识碎片/MarkDown 文本解析成 HTML 并生成大纲" },
  { text: "Maven 中央仓库发包流程", link: "/知识碎片/Maven 中央仓库发包流程" },
  { text: "MinIO+Docker 从零搭建一个文件存储服务", link: "/知识碎片/MinIO+Docker 从零搭建一个文件存储服务" },
  { text: "MyBatis 整合多数据源", link: "/知识碎片/MyBatis 整合多数据源" },
  { text: "MySQL 一棵 B + 树可以存多少条数据？", link: "/知识碎片/MySQL 一棵 B + 树可以存多少条数据？" },
  { text: "MySQL 字符串日期格式转换", link: "/知识碎片/MySQL 字符串日期格式转换" },
  { text: "MySQL 的 Char 并不一定是定长", link: "/知识碎片/MySQL 的 Char 并不一定是定长" },
  { text: "MySQL8 绿色版安装", link: "/知识碎片/MySQL8 绿色版安装" },
  {
    text: "MySQL基础知识：DDL、DML、DQL、DCL及TPL的使用",
    link: "/知识碎片/MySQL基础知识：DDL、DML、DQL、DCL及TPL的使用",
  },
  { text: "Nacos 配置中心搭建", link: "/知识碎片/Nacos 配置中心搭建" },
  { text: "OJ 竞赛排行榜统计逻辑设计与代码实现", link: "/知识碎片/OJ 竞赛排行榜统计逻辑设计与代码实现" },
  { text: "Oracle到MySQL函数替换方案汇总", link: "/知识碎片/Oracle到MySQL函数替换方案汇总" },
  { text: "RESTful 接口实现与测试( Spring Boot )", link: "/知识碎片/RESTful 接口实现与测试( Spring Boot )" },
  { text: "RabbitMQ一死信队列介绍和应用", link: "/知识碎片/RabbitMQ一死信队列介绍和应用" },
  {
    text: "Redis 实现文章点赞功能(附带前后端代码、数据库)",
    link: "/知识碎片/Redis 实现文章点赞功能(附带前后端代码、数据库)",
  },
  { text: "Redission 解锁异常解决方案", link: "/知识碎片/Redission 解锁异常解决方案" },
  { text: "SpringBoot + Quartz 简易定时任务", link: "/知识碎片/SpringBoot + Quartz 简易定时任务" },
  { text: "SpringBoot 整合 ELK 实现日志采集与监控", link: "/知识碎片/SpringBoot 整合 ELK 实现日志采集与监控" },
  {
    text: "SpringBoot 整合 Minio全流程（从安装 Minio 到应用）",
    link: "/知识碎片/SpringBoot 整合 Minio全流程（从安装 Minio 到应用）",
  },
  {
    text: "SpringBoot 项目中快速引入 Rabbit MQ 通用做法",
    link: "/知识碎片/SpringBoot 项目中快速引入 Rabbit MQ 通用做法",
  },
  { text: "SpringBoot通过自定义注解实现多数据源", link: "/知识碎片/SpringBoot通过自定义注解实现多数据源" },
  { text: "SpringSecurity 整合 Oauth2", link: "/知识碎片/SpringSecurity 整合 Oauth2" },
  { text: "Springboot 引入 Nacos ( Windows 版)", link: "/知识碎片/Springboot 引入 Nacos ( Windows 版)" },
  { text: "String 的 intern() 方法", link: "/知识碎片/String 的 intern() 方法" },
  { text: "Synchronized 关键字详解", link: "/知识碎片/Synchronized 关键字详解" },
  {
    text: "TextCNN 文本分类模型在文章评论审核中的实现与部署",
    link: "/知识碎片/TextCNN 文本分类模型在文章评论审核中的实现与部署",
  },
  { text: "Vue3 快速实现文件上传 OSS", link: "/知识碎片/Vue3 快速实现文件上传 OSS" },
  { text: "WebSocket 前后端联调使用", link: "/知识碎片/WebSocket 前后端联调使用" },
  {
    text: "Websocket.+ Spring-SseEmitter3 实现讯飞星火Java客户端",
    link: "/知识碎片/Websocket.+ Spring-SseEmitter3 实现讯飞星火Java客户端",
  },
  { text: "fail-fast 机制是什么？", link: "/知识碎片/fail-fast 机制是什么？" },
  { text: "主页", link: "/知识碎片/" },
  {
    text: "《贯穿设计模式》第三方登录实践[附前后端完整过程及测试]",
    link: "/知识碎片/《贯穿设计模式》第三方登录实践[附前后端完整过程及测试]",
  },
  { text: "【Ajax】异步通信", link: "/知识碎片/【Ajax】异步通信" },
  { text: "【Java基础】消灭魔法值-常量&枚举详述", link: "/知识碎片/【Java基础】消灭魔法值-常量&枚举详述" },
  { text: "【Redis应用】UV统计", link: "/知识碎片/【Redis应用】UV统计" },
  { text: "【版本控制】Git快速上手", link: "/知识碎片/【版本控制】Git快速上手" },
  { text: "【设计模式】七大设计原则", link: "/知识碎片/【设计模式】七大设计原则" },
  { text: "【设计模式】命令模式入门实战", link: "/知识碎片/【设计模式】命令模式入门实战" },
  {
    text: "【设计模式】装饰者模式，及其在JDK源码中的应用",
    link: "/知识碎片/【设计模式】装饰者模式，及其在JDK源码中的应用",
  },
  { text: "什么是接口的幂等性，如何保证接口的幂等性？", link: "/知识碎片/什么是接口的幂等性，如何保证接口的幂等性？" },
  { text: "从聚合搜索项目视角入门 ElasticSearch", link: "/知识碎片/从聚合搜索项目视角入门 ElasticSearch" },
  { text: "伙伴匹配引入 GEO 实现搜索附近用户", link: "/知识碎片/伙伴匹配引入 GEO 实现搜索附近用户" },
  { text: "使用 AOP+自定义注解实现日志打印", link: "/知识碎片/使用 AOP+自定义注解实现日志打印" },
  { text: "使用 FreeMarker 模板引擎生成代码", link: "/知识碎片/使用 FreeMarker 模板引擎生成代码" },
  { text: "使用 Java 程序自动构建 jar 包", link: "/知识碎片/使用 Java 程序自动构建 jar 包" },
  { text: "使用 NVM 快捷管理 Node 版本（Win版）", link: "/知识碎片/使用 NVM 快捷管理 Node 版本（Win版）" },
  { text: "使用 Picocli 开发 Java 命令行", link: "/知识碎片/使用 Picocli 开发 Java 命令行" },
  { text: "使用 canal 实现增量订阅和消费", link: "/知识碎片/使用 canal 实现增量订阅和消费" },
  { text: "使用后端代码生成器，提高开发效率", link: "/知识碎片/使用后端代码生成器，提高开发效率" },
  { text: "使用对象存储实现文件上传下载", link: "/知识碎片/使用对象存储实现文件上传下载" },
  { text: "使用第三方服务(宝塔)快速部署项目", link: "/知识碎片/使用第三方服务(宝塔)快速部署项目" },
  { text: "函数式接口的使用", link: "/知识碎片/函数式接口的使用" },
  { text: "利用局域网搭建虚拟机实现访问项目", link: "/知识碎片/利用局域网搭建虚拟机实现访问项目" },
  { text: "前端初始化 Ant Design Pro 笔记", link: "/知识碎片/前端初始化 Ant Design Pro 笔记" },
  { text: "前端必学的开发框架，Ant Design Pro", link: "/知识碎片/前端必学的开发框架，Ant Design Pro" },
  { text: "十种 SQL 的写法", link: "/知识碎片/十种 SQL 的写法" },
  { text: "后端 Spring Boot 万用模板使用", link: "/知识碎片/后端 Spring Boot 万用模板使用" },
  { text: "后端如何编写单元测试？ ", link: "/知识碎片/后端如何编写单元测试？ " },
  { text: "后端项目经典分层架构介绍", link: "/知识碎片/后端项目经典分层架构介绍" },
  { text: "基于 GA 遗传算法的智能组题模块的设计与应用", link: "/知识碎片/基于 GA 遗传算法的智能组题模块的设计与应用" },
  { text: "基于 Redis 实现短信登录", link: "/知识碎片/基于 Redis 实现短信登录" },
  { text: "基于 Session 实现短信登录", link: "/知识碎片/基于 Session 实现短信登录" },
  { text: "基于自定义注解的 Redisson 分布式锁实现", link: "/知识碎片/基于自定义注解的 Redisson 分布式锁实现" },
  {
    text: "多语言代码沙箱的设计与实现(OJ 在线判题系统)",
    link: "/知识碎片/多语言代码沙箱的设计与实现(OJ 在线判题系统)",
  },
  {
    text: "如何处理 CompletableFuture 中的两种异常(智能BI项目)",
    link: "/知识碎片/如何处理 CompletableFuture 中的两种异常(智能BI项目)",
  },
  { text: "如何快速忽略 Git 文件提交？", link: "/知识碎片/如何快速忽略 Git 文件提交？" },
  { text: "如何解决数据查询为空的 Bug？", link: "/知识碎片/如何解决数据查询为空的 Bug？" },
  { text: "如何解决缓存击穿？", link: "/知识碎片/如何解决缓存击穿？" },
  { text: "如何高效测试接口？自动生成接口文档", link: "/知识碎片/如何高效测试接口？自动生成接口文档" },
  {
    text: "定义API并生成代码（ Go 微服务框架 Kratos ）",
    link: "/知识碎片/定义API并生成代码（ Go 微服务框架 Kratos ）",
  },
  { text: "实现主题换肤( CSS 变量 + 类名切换)", link: "/知识碎片/实现主题换肤( CSS 变量 + 类名切换)" },
  { text: "常用的存储优化方法", link: "/知识碎片/常用的存储优化方法" },
  { text: "常用的性能优化方法", link: "/知识碎片/常用的性能优化方法" },
  { text: "并发问题的三大根源是什么？", link: "/知识碎片/并发问题的三大根源是什么？" },
  { text: "开发企业微信群机器人，实现定时提醒", link: "/知识碎片/开发企业微信群机器人，实现定时提醒" },
  { text: "快速学会为开源项目做贡献", link: "/知识碎片/快速学会为开源项目做贡献" },
  { text: "提示工程进阶技巧（大模型）", link: "/知识碎片/提示工程进阶技巧（大模型）" },
  { text: "整合Spring JDBC操作数据库", link: "/知识碎片/整合Spring JDBC操作数据库" },
  { text: "文章评论功能前后端实现方案总结", link: "/知识碎片/文章评论功能前后端实现方案总结" },
  { text: "模板引擎-Thymeleaf与Freemarker", link: "/知识碎片/模板引擎-Thymeleaf与Freemarker" },
  { text: "浅谈 cookie 和 session", link: "/知识碎片/浅谈 cookie 和 session" },
  {
    text: "海量数据场景面试题：出现频率最高的 100 个词",
    link: "/知识碎片/海量数据场景面试题：出现频率最高的 100 个词",
  },
  { text: "深入了解进程和线程：概念、区别和优化", link: "/知识碎片/深入了解进程和线程：概念、区别和优化" },
  { text: "状态机概念以及使用", link: "/知识碎片/状态机概念以及使用" },
  { text: "玩转异步编程利器 CompletableFuture", link: "/知识碎片/玩转异步编程利器 CompletableFuture" },
  { text: "理解 IO 多路复用", link: "/知识碎片/理解 IO 多路复用" },
  { text: "理解原码、反码、补码", link: "/知识碎片/理解原码、反码、补码" },
  { text: "理解进程，线程，协程", link: "/知识碎片/理解进程，线程，协程" },
  { text: "用 QQ 邮箱实现验证码功能", link: "/知识碎片/用 QQ 邮箱实现验证码功能" },
  { text: "用@Validated注解实现非空校验", link: "/知识碎片/用@Validated注解实现非空校验" },
  { text: "用四种锁实现加入队伍功能(伙伴匹配系统)", link: "/知识碎片/用四种锁实现加入队伍功能(伙伴匹配系统)" },
  {
    text: "用布隆过滤器实现检查用户名是否存在(用户注册)",
    link: "/知识碎片/用布隆过滤器实现检查用户名是否存在(用户注册)",
  },
  {
    text: "缓存穿透、缓存击穿、缓存雪崩的场景以及解决方法",
    link: "/知识碎片/缓存穿透、缓存击穿、缓存雪崩的场景以及解决方法",
  },
  { text: "设计模式实践（OJ判题和聚合搜索)", link: "/知识碎片/设计模式实践（OJ判题和聚合搜索)" },
  { text: "详解 SpringBoot 自定义 Starter", link: "/知识碎片/详解 SpringBoot 自定义 Starter" },
  { text: "通过 Windows 脚本执行打包操作", link: "/知识碎片/通过 Windows 脚本执行打包操作" },
  { text: "阿里云对象存储 OSS", link: "/知识碎片/阿里云对象存储 OSS" },
  { text: "阿里云短信服务实现手机验证码", link: "/知识碎片/阿里云短信服务实现手机验证码" },
  { text: "面试超高频考点：HashMap 源码逐行解析", link: "/知识碎片/面试超高频考点：HashMap 源码逐行解析" },
];
